name: Build Flipper Application Package

env:
  APP_ID: hpkns_hello

on:
  push:
    tags:
      - "v**"
    branches:
      - main
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flipper Zero Firmware
        uses: actions/checkout@v3
        with:
          repository: flipperdevices/flipperzero-firmware
          path: flipper
      - name: Checkout application repository
        uses: actions/checkout@v3
        with:
          path: flipper/applications_user/${{ env.APP_ID }}
      - name: Build FAPs
        run: |
          pushd flipper
          ./fbt fap_dist
          popd
      - name: Upload FAP artifact
        uses: actions/upload-artifact@v3
        with:
          name: flipper-application-package
          path: flipper/dist/f7-D/apps/apps/*/${{ env.APP_ID }}.fap
          if-no-files-found: error
      - name: Create release if a semver tag is pushed
        if: ${{ github.ref_type == 'tag' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            flipper/dist/f7-D/apps/apps/*/${{ env.APP_ID }}.fap

