name: Build Flipper Application Package

env:
  APP_ID: hpkns_hello

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flipper Zero Firmware
        uses: actions/checkout@v3
        with:
          repository: flipperdevices/flipperzero-firmware
          path: flipper
      - name: Checkout application repository
        uses: actions/checkout@v3
        with:
          path: flipper/applications_user/$APP_ID
      - name: Build FAPs
        run: |
          pushd flipper
          ls -al .
          ./fbt fap_dist
          popd
      - name: Upload FAP artifact
        uses: actions/upload-artifact@v3
        with:
          name: flipper-application-package
          path: flipperzero-firmware/dist/f7-D/apps/apps/*/${APP_ID}.fap

